name: Build & Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK via Eclipse Temurin
          java-version: '17'
      - name: Build with Maven
        run: ./mvnw -ntp package
      - name: Dump Target
        run: ls -Alth target && ls -Alth .mvn
